# TODO check line endings too
name: Check BOMs

on: push

jobs:
  check-bom:
    name: check files for BOMs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Check if any file has a BOM
        uses: arma-actions/bom-check@v1.0
