name: PowerShell Core CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # TODO maybe use pester to run psscriptanalyzer?
  lint:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update PSScriptAnalyzer to latest version
        run: Install-Module -Force -Scope CurrentUser -Name PSScriptAnalyzer
        shell: pwsh

      - name: run PSScriptAnalyzer
        run: Invoke-ScriptAnalyzer -EnableExit -Settings PSScriptAnalyzerSettings.psd1 -Recurse -Path "."
        shell: pwsh

  # TODO check code coverage
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update Pester to latest version
        run: Install-Module -Force -Scope CurrentUser -Name Pester
        shell: pwsh

      - name: Run pester tests
        run: Invoke-Pester -EnableExit -Path "."
        shell: pwsh
