name: Main PowerShell Core workflow

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Update Pester to latest version
      run: Install-Module -Name Pester -Force -SkipPublisherCheck
      shell: pwsh

    - name: Run pester tests
      run: Invoke-Pester
      shell: pwsh
